** 2026-05-26 Feedback
Not complete. Just what I had time for this morning.
*** general
I see sync resets everywhere.
Does *everything* need to be reset?
Normally we separate control from data and only control needs to be reset.


*** ALU
alu_control should be a typedef enum, use symbolic name instead of value

line 14 overflow: this looks wrong to me though i've not simulated it
https://www.c-jump.com/CIS77/CPU/Overflow/lecture.html
can you overflow on opcodes other than add and sub?
overflow detection doesn't seem right to me: carry_in != carry_out is what i'd expect for 2s complement
i'd expect differences based on opcode
because your opcode is a number (not an enum) i can't read your RTL

your alu doesn't seem to have a "size" concept: 32bit vs 16bit vs 8bit for example

#+begin_example
assign overflow = (alu_control == 4'b0110) ?  // your opcode doesn't do anything
((a[31] != b[31]) && (a[31] != result[31])) : // CASE1: a31!=b31: rhs is a31!=r31
 (a[31] == b[31]) && (a[31] != result[31]);   // CASE0: a31==b31: rhs exactly the same, wtf?
#+end_example
*** alu_control
you made the module name the same as a port name on the same module, lol
this should be an enumerated type, in fact this is the mother of all examples of when to use an enum

your always_comb needs:
1. a default output assignment -- MUST HAVE, REQUIRED
2. a default for case statementf -- NOT REQUIRED BUT USUALLY GOOD

#+begin_example
always_comb begin
   my_output_of_block = 0; // THIS IS THE DEFAULT OUTPUT ASSIGNMENT
   case (somebullshit)
      0 : my_output_of_block = 0;
      1 : my_output_of_block = 1;
      default :  my_output_of_block = 0; // THIS IS THE DEFAULT FOR CASE STATEMENT
   endcase
end
#+end_example

don't use the word "wire" in you comment, duh, you'll grep for it later and be surprised
*** register_file.sv
1. line 22: why is register *not* updated when rd_addr == 0? can you not read address 0?
